package fi.tuni.tamk.web_blog_app.userdata;

import lombok.Data;
import org.springframework.stereotype.Component;
import javax.persistence.*;
import java.util.ArrayList;

/**
 * Class which holds user information.
 */
@Data
@Entity
@Component
public class UserData {

    /**
     * Autogenerated Long id
     */
    private @Id @GeneratedValue(strategy = GenerationType.IDENTITY) Long id;
    /**
     * User username String
     */
    private String username;
    /**
     * User password String
     */
    private String password;
    /**
     * User likedBlogPostIds ArrayList
     */
    private ArrayList<Long> likedBlogPostIds = new ArrayList<>();
    /**
     * User dislikedBlogPostIds ArrayList
     */
    private ArrayList<Long> dislikedBlogPostIds = new ArrayList<>();

    UserData() {}

    public UserData(String username,
                    String password) {
        this.username = username;
        this.password = password;

    }
}